
import java.awt.event.ActionEvent;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MatheusF
 */
public class CalcUi extends javax.swing.JFrame {

    float num1 = 0, num2 = 0, result = 0;
    char operator;
    private boolean abrirParenteses = true;

    /**
     * Creates new form CalcUi
     */
    public CalcUi() {
        initComponents();
    }

    private void abrirParenteses() {
        jTResult.setText(jTResult.getText() + "(");
    }

    private void fecharParenteses() {
        jTResult.setText(jTResult.getText() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalculadora = new javax.swing.JPanel();
        jResult = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTResult = new javax.swing.JTextField();
        jTCalc = new javax.swing.JTextField();
        jNumeros = new javax.swing.JPanel();
        jBLimpa = new javax.swing.JButton();
        jBParentes = new javax.swing.JButton();
        jBPorcento = new javax.swing.JButton();
        jBDivi = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBVezes = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jBMenos = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBMais = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBVirgula = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        jCalculadora.setBackground(new java.awt.Color(102, 102, 102));
        jCalculadora.setMaximumSize(new java.awt.Dimension(600, 600));
        jCalculadora.setMinimumSize(new java.awt.Dimension(600, 600));
        jCalculadora.setPreferredSize(new java.awt.Dimension(600, 600));

        jResult.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(466, 56));

        jTResult.setBackground(new java.awt.Color(255, 255, 255));
        jTResult.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jTResult.setText(" ");
        jTResult.setBorder(null);
        jTResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTResultActionPerformed(evt);
            }
        });

        jTCalc.setEditable(false);
        jTCalc.setBackground(new java.awt.Color(255, 255, 255));
        jTCalc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTCalc.setForeground(new java.awt.Color(0, 0, 0));
        jTCalc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTCalc.setBorder(null);
        jTCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTResult, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTCalc, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTResult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jResultLayout = new javax.swing.GroupLayout(jResult);
        jResult.setLayout(jResultLayout);
        jResultLayout.setHorizontalGroup(
            jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        jResultLayout.setVerticalGroup(
            jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jNumeros.setBackground(new java.awt.Color(102, 102, 102));

        jBLimpa.setBackground(new java.awt.Color(0, 0, 0));
        jBLimpa.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jBLimpa.setForeground(new java.awt.Color(255, 255, 255));
        jBLimpa.setText("AC");
        jBLimpa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBLimpa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBLimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpaActionPerformed(evt);
            }
        });

        jBParentes.setBackground(new java.awt.Color(0, 0, 0));
        jBParentes.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBParentes.setForeground(new java.awt.Color(255, 255, 255));
        jBParentes.setText("()");
        jBParentes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBParentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBParentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBParentesActionPerformed(evt);
            }
        });

        jBPorcento.setBackground(new java.awt.Color(0, 0, 0));
        jBPorcento.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jBPorcento.setForeground(new java.awt.Color(255, 255, 255));
        jBPorcento.setText("%");
        jBPorcento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPorcento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPorcento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPorcentoActionPerformed(evt);
            }
        });

        jBDivi.setBackground(new java.awt.Color(0, 0, 0));
        jBDivi.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBDivi.setForeground(new java.awt.Color(255, 255, 255));
        jBDivi.setText("÷");
        jBDivi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBDivi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBDivi.setPreferredSize(new java.awt.Dimension(18, 34));
        jBDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDiviActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(0, 0, 0));
        jB7.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB7.setForeground(new java.awt.Color(255, 255, 255));
        jB7.setText("7");
        jB7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setBackground(new java.awt.Color(0, 0, 0));
        jB8.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB8.setForeground(new java.awt.Color(255, 255, 255));
        jB8.setText("8");
        jB8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(0, 0, 0));
        jB9.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB9.setForeground(new java.awt.Color(255, 255, 255));
        jB9.setText("9");
        jB9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jBVezes.setBackground(new java.awt.Color(0, 0, 0));
        jBVezes.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBVezes.setForeground(new java.awt.Color(255, 255, 255));
        jBVezes.setText("x");
        jBVezes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBVezes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVezesActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(0, 0, 0));
        jB4.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB4.setForeground(new java.awt.Color(255, 255, 255));
        jB4.setText("4");
        jB4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(0, 0, 0));
        jB5.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB5.setForeground(new java.awt.Color(255, 255, 255));
        jB5.setText("5");
        jB5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setBackground(new java.awt.Color(0, 0, 0));
        jB6.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB6.setForeground(new java.awt.Color(255, 255, 255));
        jB6.setText("6");
        jB6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jBMenos.setBackground(new java.awt.Color(0, 0, 0));
        jBMenos.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBMenos.setForeground(new java.awt.Color(255, 255, 255));
        jBMenos.setText("-");
        jBMenos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenosActionPerformed(evt);
            }
        });

        jB1.setBackground(new java.awt.Color(0, 0, 0));
        jB1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB1.setForeground(new java.awt.Color(255, 255, 255));
        jB1.setText("1");
        jB1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(0, 0, 0));
        jB2.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB2.setForeground(new java.awt.Color(255, 255, 255));
        jB2.setText("2");
        jB2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(0, 0, 0));
        jB3.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB3.setForeground(new java.awt.Color(255, 255, 255));
        jB3.setText("3");
        jB3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jBMais.setBackground(new java.awt.Color(0, 0, 0));
        jBMais.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBMais.setForeground(new java.awt.Color(255, 255, 255));
        jBMais.setText("+");
        jBMais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBMais.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMaisActionPerformed(evt);
            }
        });

        jB0.setBackground(new java.awt.Color(0, 0, 0));
        jB0.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jB0.setForeground(new java.awt.Color(255, 255, 255));
        jB0.setText("0");
        jB0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jBVirgula.setBackground(new java.awt.Color(0, 0, 0));
        jBVirgula.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBVirgula.setForeground(new java.awt.Color(255, 255, 255));
        jBVirgula.setText(",");
        jBVirgula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBVirgula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVirgulaActionPerformed(evt);
            }
        });

        jBDelete.setBackground(new java.awt.Color(0, 0, 0));
        jBDelete.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jBDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBDelete.setText("⌫");
        jBDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBIgual.setBackground(new java.awt.Color(0, 0, 0));
        jBIgual.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jBIgual.setForeground(new java.awt.Color(255, 255, 255));
        jBIgual.setText("=");
        jBIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNumerosLayout = new javax.swing.GroupLayout(jNumeros);
        jNumeros.setLayout(jNumerosLayout);
        jNumerosLayout.setHorizontalGroup(
            jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNumerosLayout.createSequentialGroup()
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNumerosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jNumerosLayout.createSequentialGroup()
                                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jNumerosLayout.createSequentialGroup()
                                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                                        .addComponent(jBParentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                                        .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBVezes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMenos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBDivi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                        .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jNumerosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBVirgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNumerosLayout.createSequentialGroup()
                                .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBMais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jNumerosLayout.setVerticalGroup(
            jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNumerosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBParentes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNumerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jCalculadoraLayout = new javax.swing.GroupLayout(jCalculadora);
        jCalculadora.setLayout(jCalculadoraLayout);
        jCalculadoraLayout.setHorizontalGroup(
            jCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCalculadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(jCalculadoraLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jCalculadoraLayout.setVerticalGroup(
            jCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCalculadoraLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTResultActionPerformed

    private void jBDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDiviActionPerformed
        if (evt.getSource() == jBDivi) {
            num1 = Float.parseFloat(jTResult.getText());
            operator = '/';
            jTResult.setText(jTResult.getText() + "÷");
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            jTResult.setText("");
        }
    }//GEN-LAST:event_jBDiviActionPerformed

    private void jBParentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBParentesActionPerformed
        if (abrirParenteses) {
            abrirParenteses();
            abrirParenteses = false;
        } else {
            fecharParenteses();
            abrirParenteses = true;
        }
    }//GEN-LAST:event_jBParentesActionPerformed

    private void jBLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpaActionPerformed

        if (evt.getSource() == jBLimpa) {
            jTResult.setText("");
            jTCalc.setText("");
        }
    }//GEN-LAST:event_jBLimpaActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed

        if (evt.getSource() == jB0) {
            jTResult.setText(jTResult.getText() + "0");
        }
    }//GEN-LAST:event_jB0ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        if (evt.getSource() == jB7) {
            jTResult.setText(jTResult.getText() + "7");
        }

    }//GEN-LAST:event_jB7ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        if (evt.getSource() == jB1) {
            jTResult.setText(jTResult.getText() + "1");
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed
        if (evt.getSource() == jBIgual) {
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            num2 = Float.parseFloat(jTResult.getText());

            switch (operator) {
                case '+':
                    result = num1 + num2;
                    break;

                case '-':
                    result = num1 - num2;
                    break;

                case '*':
                    result = num1 * num2;
                    break;

                case '/':
                    result = num1 / num2;
                    break;
                case '%':
                    result = (num1 / 100) * num2;
                    break;
            }

            jTResult.setText(String.valueOf(result));
            num1 = result;
        }
    }//GEN-LAST:event_jBIgualActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        if (evt.getSource() == jB2) {
            jTResult.setText(jTResult.getText() + "2");
        }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        if (evt.getSource() == jB3) {
            jTResult.setText(jTResult.getText() + "3");
        }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        if (evt.getSource() == jB4) {
            jTResult.setText(jTResult.getText() + "4");
        }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        if (evt.getSource() == jB5) {
            jTResult.setText(jTResult.getText() + "5");
        }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        if (evt.getSource() == jB6) {
            jTResult.setText(jTResult.getText() + "6");
        }
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        if (evt.getSource() == jB8) {
            jTResult.setText(jTResult.getText() + "8");
        }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        if (evt.getSource() == jB9) {
            jTResult.setText(jTResult.getText() + "9");
        }
    }//GEN-LAST:event_jB9ActionPerformed

    private void jBVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVirgulaActionPerformed
        if (evt.getSource() == jBVirgula) {
            jTResult.setText(jTResult.getText().concat("."));
        }
    }//GEN-LAST:event_jBVirgulaActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        if (evt.getSource() == jBDelete) {
            String string = jTResult.getText();
            jTResult.setText(jTResult.getText().substring(0, jTResult.getText().length() - 1));
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMaisActionPerformed
        if (evt.getSource() == jBMais) {
            num1 = Float.parseFloat(jTResult.getText());
            operator = '+';
            jTResult.setText(jTResult.getText() + "+");
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            jTResult.setText("");
        }
    }//GEN-LAST:event_jBMaisActionPerformed

    private void jBMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenosActionPerformed
        if (evt.getSource() == jBMenos) {
            num1 = Float.parseFloat(jTResult.getText());
            operator = '-';
            jTResult.setText(jTResult.getText() + "-");
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            jTResult.setText("");
        }
    }//GEN-LAST:event_jBMenosActionPerformed

    private void jBVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVezesActionPerformed
        if (evt.getSource() == jBVezes) {
            num1 = Float.parseFloat(jTResult.getText());
            operator = '*';
            jTResult.setText(jTResult.getText() + "x");
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            jTResult.setText("");
        }
    }//GEN-LAST:event_jBVezesActionPerformed

    private void jBPorcentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPorcentoActionPerformed
        if (evt.getSource() == jBPorcento) {
            num1 = Float.parseFloat(jTResult.getText());
            operator = '%';
            jTResult.setText(jTResult.getText() + "%");
            jTCalc.setText(jTCalc.getText() + jTResult.getText());
            jTResult.setText("");
        }
    }//GEN-LAST:event_jBPorcentoActionPerformed

    private void jTCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcUi().setVisible(true);

            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBDivi;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBLimpa;
    private javax.swing.JButton jBMais;
    private javax.swing.JButton jBMenos;
    private javax.swing.JButton jBParentes;
    private javax.swing.JButton jBPorcento;
    private javax.swing.JButton jBVezes;
    private javax.swing.JButton jBVirgula;
    private javax.swing.JPanel jCalculadora;
    private javax.swing.JPanel jNumeros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jResult;
    private javax.swing.JTextField jTCalc;
    private javax.swing.JTextField jTResult;
    // End of variables declaration//GEN-END:variables
}
